### ISSUE TITLE
Neo4j 4.0.x Limit and Skip clauses now expect params to be Neo4j.int

### ISSUE THREAD

**Issue by ChristopheVandePoel** [jamesfer/cypher-query-builder#159]
I refer to the following issue on the driver repo:
https://github.com/neo4j/neo4j-javascript-driver/issues/547

We are in the progress of upgrading our Neo4j to 4.x and ran into the above error when using `.limit(10)` and `.skip(10)` as provided by this repository.

Steps to reproduce
Against a Neo4j 4.x, run:
```javascript
     query.match([node(name, '')])
               .return(name)
               .limit(10)
```

expected result: first 10 records to be returned.
actual result: error thrown `LIMIT: Invalid input. '10.0' is not a valid value `

current workaround
replace all `query.limit()` and `query.skip()` calls with a `query.raw()` value
```
query.raw(`SKIP $skip`, { skip: neo4j.int(this.options.skip) })
```

Proposed fix
Replace the implementation of the limit and skip with a compatible version:
```skip.ts
    this.amountParam = this.addParam(neo4j.int(amount), 'skipCount');
```

This should be bw/fw compatible, but might result in cypher snapshots during tests (like with ours) to fail.

**Comment by jamesfer** [comment]
Hey there. Thanks for the detailed bug report. I've created a fix and should be able to deploy it soon.
