### ISSUE TITLE
plain object return is not supported

### ISSUE THREAD

**Issue by seoker** [jamesfer/cypher-query-builder#27]
```
db
  .matchNode('foo', 'Foo', { id: "123" })
  .with(['foo', 'foo {.*} AS snapshot'])
  .return(['foo', 'snapshot'])
```
leads to
```
MATCH (foo:Foo { id: "123" }) WITH foo, foo {.*} AS snapshot RETURN foo, snapshot
```

The result `snapshot` will be `null` since the raw response won't be `identity`, `labels`, and `properties` but the object itself.

**Comment by jamesfer** [comment]
This should be supported in v3.3.0 which I just released then. I'll close this issue for now, but let me know if there are still issues.
