### ISSUE TITLE
options for setValues doesn't work

### ISSUE THREAD

**Issue by seoker** [jamesfer/cypher-query-builder#30]
Either
```javascript
setValues({ foo: foo }, { override: true }) // foo is an object
```
or 
```javascript
setValues({ foo: foo }, true) // foo is an object
```
are sending out
```
SET foo = $foo
```

BTW, I think default value should be `{ override: false }` to be compatible with previous versions

**Comment by jamesfer** [comment]
When you set override to `true`, `SET foo = $foo` is the expected output because all of the properties of `foo` will be overridden. If you would like to use `+=` in cypher, pass `false` or nothing at all as `false` should be the default value anyway.

**Comment by seoker** [comment]
so, it's a document bug? lol

![image](https://user-images.githubusercontent.com/7975797/40061964-ad8eebf4-588c-11e8-809c-d5bdfad56c64.png)

**Comment by jamesfer** [comment]
Yes you were right about the documentation errors, I've fixed them in a branch so they should be released soon. Using the `+=` operator (`false`) should always be the default and I'm working on making that more consistent across all the `set` family of methods.
