### ISSUE TITLE
between does not generate valid cypher

### ISSUE THREAD

**Issue by jshthornton** [jamesfer/cypher-query-builder#31]
**Current:**
```
MATCH (n:Label)
WHERE n.date <= $upper,n.date >= $lower
RETURN n;
```
`Invalid input ',': expected an identifier character, whitespace, '.',`

**Expected:**
```
MATCH (n:Label)
WHERE $lower <= n.date <= $upper
RETURN n;
```

**Comment by jamesfer** [comment]
Thanks for letting me know. Hopefully, a fix will be ready in the next release.

**Comment by jamesfer** [comment]
This has been deployed in `3.4.1`
