### ISSUE TITLE
Question: relationship between existing nodes

### ISSUE THREAD

**Issue by ValiDraganescu** [jamesfer/cypher-query-builder#40]
Hi, I like this library, makes things easy. Could you please provide an example on how to add a relationship between two existing nodes?
I tries this:
`const query = this.db.match([
			node("a", this.modelType.constructor.name, {uuid: uuidFrom}),
			node("b", new toType().constructor.name, {uuid: uuidTo})
		]).create([
			node("a"),
			relation("out", `:${name}`),
			node("b")
		]);`
but this results in 
`MATCH (a:User { uuid: '2c0d4196-0851-4ae2-b764-37696bd52a20' })(b:Token { uuid: '98a4551c-326d-417e-9f80-54151fb5b6e0' })
    CREATE (a)-[:HasToken]->(b);
`
there is a comma missing between node a and b in the MATCH operation.

Thank you!

Later edit: 
I finally managed to do it with this query:
`const query = this.db.matchNode("a", this.modelType.constructor.name, {uuid: uuidFrom})
			.matchNode("b", new toType().constructor.name, {uuid: uuidTo})
			.create([
				node("a"),
				relation("out", `rel:${name}`),
				node("b")
			]);`
It seems to be what I need. Do I miss something here? Maybe there are some performance issues because of the two matches?

**Comment by jamesfer** [comment]
There shouldn't be any performance penalties between using a single `MATCH` or multiple, at least that I know of.

As far as a simpler way to write it, try:
```javascript
this.db.match([
  [ node("a", .......) ],
  [ node("b", .......) ],
]);
```
When using distinct patterns with `match` (ones that are separated by a comma), each pattern needs to be in it's own array.

**Comment by jamesfer** [comment]
I'm going to close this but feel free to ask more questions if you have them.

**Comment by ValiDraganescu** [comment]
Thanks! I got it fixed. Now I'm fighting with making neo4j work on AWS EC2, it works locally but not when trying to connect remotely. But of course, this is not you issue anymore 👍
