### ISSUE TITLE
ReferenceError: node is not defined

### ISSUE THREAD

**Issue by ooddaa** [jamesfer/cypher-query-builder#53]
Hi James,

I've been playing with your query-builder, but stumbled upon a few problems:

1. Whenever I try to implement a standalone query like

```
query.merge([
  node('user', 'User', { id: 1 }),
  relation('out', 'rel', 'OwnsProject'),
  node('project', 'Project', { id: 20 }),
])
```
I get a 
`ReferenceError: node is not defined. `

2. Importing cypher does not work for me for some reason.
```
import cypher from 'cypher-query-builder'
console.log(cypher) // undefined 
```

So I can't get 'node'/'relation' functions to work (either standalone, or as method of cypher).
How do I import cypher? Or, rather, where do I get 'node' and 'relation' functions from?

3. This query works perfectly fine
```
db.matchNode('stuff', 'Stuff')
    .return('stuff')
    .run()
    .then(result => console.log(result))
```

Many thanks!

**Comment by jamesfer** [comment]
Sorry @ooddaa I only just got round to looking at this. I'm glad you found a solution. Let me know if there are any other issues.
