### ISSUE TITLE
Need help building some queries.

### ISSUE THREAD

**Issue by purplemana** [jamesfer/cypher-query-builder#69]
How do I do these?

- MATCH (n) DETACH DELETE n
- MATCH (n) RETURN count(*) as total

**Comment by purplemana** [comment]
Also, is every `Query` instance immutable? E.g. can I do this?

    const matchN = new Query().raw(`match (n)`);
    const detachDeleteN = matchN.detachDelete("n"); // is this the right syntax?
    const countN = matchN.raw(`RETURN count(*) as total`); // only works if matchN still is immutable.

**Comment by jamesfer** [comment]
To answer your original question, I would write them like this:
```javascript
// MATCH (n) DETACH DELETE n
new Query().matchNode('n').detachDelete('n');

// MATCH (n) RETURN count(*) as total
new Query().matchNode('n').return({ 'count(*)': 'total' });
```
If you already have a connection to your database, you can use `connection.matchNode(....` instead of manually creating a `new Query`.

Currently, queries are not immutable; calling a method on the query object will modify it. This is something that I'm planning to improve in the next major version. So your code above might need to be changed to:
```javascript
const matchN = () => new Query().matchNode('n');
const detachDeleteN = matchN().detachDelete('n');
const countN = matchN().raw(`RETURN count(*) as total`);
```

I'm going to close this, but feel free reply if you have more questions :)

**Comment by purplemana** [comment]
Perfect and thanks for the super prompt response 😃. The reason I am not using `Connection` is that I am managing transactions and parallel session in my code. I guess if `Connection` can optionally take a `neo4j.v1.Driver` instance and use that, it will make easy to use it in these conditions.

Which brings me to the additional question - Does `Connection` already provide a way to batch several queries together in a transaction? I need to create nodes and reference them in the next set of created nodes and relations. Coming from a non-graph background, I am using transactions which feel familiar. Can this can be done in a different way with Neo4J/`Connection`?

**Comment by jamesfer** [comment]
I haven't worked with transactions much in Cypher so I can't comment on what is the best way to do this but it sounds fine. 

There is currently no transaction support in the connection class but I'd be interested to see how you're doing it at the moment so I can start to plan how to incorporate it in the future. Would you mind sharing some example code if you can?

**Comment by purplemana** [comment]
Sure, here's the code for reference - https://gist.github.com/purplemana/64491ef81a389c3b58f12f28806c45ca.

I had to create a wrapper over Neo4J `Transaction` as it doesn't provide a reference to the session, and I'd need to close the underlying session once the transaction is over.

Note that the implementation keeps transactions optional and uses `session` when transactions are not provided.
